name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:   
  unit-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run unit tests
        run: npm run test
      
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
  
  check-format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci
        
      - name: Check format
        run: npm run check-format
