# This is a basic workflow to help you get started with Actions

name: Publish App

# Controls when the action will run. 
on:
  release:
    types:
      - published

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: ionic cordova build android --prod --release
          
      - name: Publish App
        run: echo Failed to publish
